logging:
  level:
    root: INFO

security:
  jwt:
    key-store: classpath:jwt.jks
    key-store-password: password
    key-pair-alias: jwt
    key-pair-password: password

server:
  port: ${SERVER_PORT}
  servlet:
    #    context-path: /api
    context-path: /
spring:
  http:
    log-request-details: true
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    hibernate:
        ddl-auto: none
#      ddl-auto: ${DDL_AUTO}
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:${DB_DBMS}://${DB_HOSTNAME}:3306/${DB_NAME}?useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  resources:
    add-mappings: false
---
spring:
  profiles: development
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

---
spring:
  profiles: production

---
spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

